version: '3'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - app-network

  node-app:
    build:
      context: .
    environment:
      SECRET: ${SECRET}
      PORT: ${PORT}
      DB_URL: mongodb://mongodb:27017/db
    ports:
      - "${PORT}:${PORT}"
    depends_on:
      - mongodb
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
